### ISSUE TITLE
Errors in console regarding Unity resources?

### ISSUE THREAD

**Issue by Luinithil** [marcin212/architect-icons#1]
Errors triggered in console for the icons-- says it can't load textures or some such. Icons are however visible as intended.

`Could not load UnityEngine.Texture2D at UI/ArchitectIcons/Structure in any active mod or in base resources.
Verse.Log:Error(String)
Verse.ContentFinder`1:Get(String, Boolean)
ArchitectIcons.Resources:FindArchitectTabCategoryIcon(String)
ArchitectIcons.MainTabWindow_Architect:DoWindowContents(Rect)
Verse.<WindowOnGUI>c__AnonStorey0:<>m__0(Int32)
UnityEngine.GUI:CallWindowDelegate(WindowFunction, Int32, Int32, GUISkin, Int32, Single, Single, GUIStyle)
`

Refer [log file here](https://gist.github.com/1e15029664b4511f9af50eb587918e8a) for full details.
Modlist in order (all mods are Staem versions unless stated):

1. Core
2. HugsLib
3. Prepare Carefully
4. Prepare Landing
5. More Planning
6. Architect Icons
7. New Zone Tools by Britnoth (Non-Steam, Ludeon forums only)
8. Temperature Tolerant
9. ModSwitch

**Comment by marcin212** [comment]
@Luinithil I know about that, it's not an issue. When you click the tab for the first time, it searches for user-defined icons, then mod-defined, then my default icon or nothing. This is my first Rimworld mod so I don't know of a way to check if an icon exists without trying to load it.These errors don't affect anything - all works fine. It's okay to ignore them. Sometime I may find a way to remove them.

**Comment by marcin212** [comment]
Fixed in new version
